# IDs configuration
id:
    # Automatically add an id field to entities
    generate: false

# Set this flag to false to not generate getter, setter, adder and remover methods
accessorMethods:      false

# Visibility of entities fields
fieldVisibility:      public

# PHP namespaces
namespaces:
    # The namespace of the generated entities
    entity: App\Entity\DTO

# The list of types and properties we want to use
types:
    # Directly Mapped Classes
    # -> INCOMING
    #
    # Data Transfer Object Super Class
    DataTransferObject :
        parent: false
        abstract: true
        properties:
            id : { range: "Text", cardinality: (0..1) }
            createdAt : { range: "Text", cardinality: (0..1) }

    # Serialization of the persisted entities
    UserDTO:
        parent: DataTransferObject
        properties:
            username: { range: "Text", cardinality: (0..1) }
            password: { range: "Text", cardinality: (0..1) }
            email: { range: "Text", cardinality: (0..1) }
            birthDate: { range: "Text", cardinality: (0..1) }
