api_platform:
    # The title of the API.
    title: 'API EPHEC Sport'

    # The description of the API.
    description: 'TFE - Technologies Informatiques - EPHEC 2018 - 2019 - Pire Joseph'

    # The version of the API.
    version: '1.0.0'


    # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
    resource_class_directories:
    - '%kernel.project_dir%/src/Entity'


    # The list of exceptions mapped to their HTTP status code.
    exception_to_status:
        # The first matching will be taken (matching with the class or with his parent (be careful with exception inheritance)

        # Custom Exceptions
        App\Exception\ItemNotFoundException : !php/const Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND
        App\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        App\Exception\InvalidIdentifierException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        App\Exception\ValidationException : !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY

        # Vendor
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        Symfony\Component\Serializer\Exception\ExceptionInterface: 500

    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
            mime_types: ['application/ld+json']

        json:
            mime_types: ['application/json']

        html:
            mime_types: ['text/html']

        # ...

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']

        jsonld:
            mime_types: ['application/ld+json']

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
