vich_uploader:
    db_driver: orm
    mappings:
        pictures:
            uri_prefix:         '%picture.uri_prefix%'
            upload_destination: '%kernel.project_dir%/public%picture.uri_prefix%'

        profilePicture:
            uri_prefix:         '%profile_picture.uri_prefix%'
            upload_destination: '%kernel.project_dir%/public%profile_picture.uri_prefix%'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
