App\Entity\User\DTO\UserDTO:
  iri: http://schema.org/Person
#  access_control: is_granted('ROLE_USER')
  itemOperations:
    get:
      method: GET
      controller: App\Controller\APIActions\User\GetUserAction
      path : "/user/{id}"

  collectionOperations:
    post:
      method: POST
      controller: App\Controller\APIActions\User\PostUserAction
      path: "/user"
      validation_groups:
        - createUser

